image: registry.geops.de/build/stretch-node-tralis:latest

before_script:
  - eval $(ssh-agent -s)

variables:
  GIT_CLEAN_FLAGS: -ffdx -e node_modules/


# Define the stages of the build which will be run in sequence
stages:
  - build
  - review

build:
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    when: on_success
    paths:
      - build/

review:
  stage: review
  dependencies:
    - build
  before_script: []
  script:
    - rsync -av build/ "/var/www/review_apps/$CI_ENVIRONMENT_SLUG/"
  environment:
    name: '$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME'
    url: 'https://$CI_ENVIRONMENT_SLUG.review-public.geops.io/'
    on_stop: stop_review
    auto_stop_in: 1 month
  tags:
    - review-apps-public

stop_review:
  stage: review
  before_script: []
  script:
    - rm -rf "/var/www/review_apps/$CI_ENVIRONMENT_SLUG"
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    name: '$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME'
    action: stop
  tags:
    - review-apps-public
